In [1]:
import pandas as pd
import numpy as np
df_train = pd.read_csv('/content/train.csv')

In [6]:
df_train.columns

Index(['text', 'label'], dtype='object')

In [2]:
df_train['label'].value_counts()

label
1    5362
0    4666
3    2159
4    1937
2    1304
5     572
Name: count, dtype: int64

In [4]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
T = Tokenizer()

In [7]:
T.fit_on_texts(df_train['text'])

In [8]:
T.word_index

{'i': 1,
 'feel': 2,
 'and': 3,
 'to': 4,
 'the': 5,
 'a': 6,
 'feeling': 7,
 'that': 8,
 'of': 9,
 'my': 10,
 'in': 11,
 'it': 12,
 'like': 13,
 'so': 14,
 'for': 15,
 'im': 16,
 'me': 17,
 'but': 18,
 'was': 19,
 'have': 20,
 'is': 21,
 'this': 22,
 'am': 23,
 'with': 24,
 'not': 25,
 'about': 26,
 'be': 27,
 'as': 28,
 'on': 29,
 'you': 30,
 'just': 31,
 'at': 32,
 'when': 33,
 'or': 34,
 'all': 35,
 'because': 36,
 'more': 37,
 'do': 38,
 'can': 39,
 'really': 40,
 'up': 41,
 't': 42,
 'are': 43,
 'by': 44,
 'very': 45,
 'know': 46,
 'been': 47,
 'if': 48,
 'out': 49,
 'myself': 50,
 'time': 51,
 'how': 52,
 'what': 53,
 'get': 54,
 'little': 55,
 'had': 56,
 'now': 57,
 'will': 58,
 'from': 59,
 'being': 60,
 'they': 61,
 'people': 62,
 'them': 63,
 'would': 64,
 'he': 65,
 'want': 66,
 'her': 67,
 'some': 68,
 'think': 69,
 'one': 70,
 'still': 71,
 'ive': 72,
 'him': 73,
 'even': 74,
 'who': 75,
 'an': 76,
 'life': 77,
 'its': 78,
 'make': 79,
 'there': 80,
 'we': 81,
 'bit': 82,
 'something': 83,
 'love': 84,
 'much': 85,
 'going': 86,
 'dont': 87,
 'things': 88,
 's': 89,
 'way': 90,
 'could': 91,
 'm': 92,
 'too': 93,
 'than': 94,
 'no': 95,
 'day': 96,
 'she': 97,
 'has': 98,
 'back': 99,
 'go': 100,
 'good': 101,
 'pretty': 102,
 'don': 103,
 'need': 104,
 'into': 105,
 'his': 106,
 'which': 107,
 'these': 108,
 'your': 109,
 'their': 110,
 'always': 111,
 'see': 112,
 'right': 113,
 'feelings': 114,
 'over': 115,
 'also': 116,
 'only': 117,
 'say': 118,
 'other': 119,
 'should': 120,
 'today': 121,
 'feels': 122,
 'work': 123,
 'then': 124,
 'after': 125,
 'did': 126,
 'around': 127,
 'again': 128,
 'were': 129,
 'cant': 130,
 'made': 131,
 'our': 132,
 'most': 133,
 'well': 134,
 'here': 135,
 'though': 136,
 'through': 137,
 'didnt': 138,
 'help': 139,
 'got': 140,
 'down': 141,
 'those': 142,
 'felt': 143,
 'never': 144,
 'any': 145,
 'every': 146,
 'someone': 147,
 'days': 148,
 'having': 149,
 'less': 150,
 'makes': 151,
 'where': 152,
 'happy': 153,
 'doing': 154,
 'enough': 155,
 'quite': 156,
 'sure': 157,
 'lot': 158,
 'many': 159,
 'why': 160,
 'away': 161,
 'look': 162,
 'find': 163,
 'ever': 164,
 'anything': 165,
 'home': 166,
 'kind': 167,
 'off': 168,
 'better': 169,
 'person': 170,
 'left': 171,
 'friends': 172,
 'without': 173,
 'own': 174,
 'before': 175,
 'everything': 176,
 'actually': 177,
 'last': 178,
 'getting': 179,
 'such': 180,
 'come': 181,
 'take': 182,
 'world': 183,
 'new': 184,
 'sometimes': 185,
 'while': 186,
 'http': 187,
 'thing': 188,
 'remember': 189,
 'trying': 190,
 'few': 191,
 'year': 192,
 'thought': 193,
 'first': 194,
 'times': 195,
 'family': 196,
 'started': 197,
 'able': 198,
 'said': 199,
 'alone': 200,
 'week': 201,
 'rather': 202,
 'try': 203,
 'making': 204,
 'long': 205,
 'let': 206,
 'already': 207,
 'keep': 208,
 'href': 209,
 'bad': 210,
 'ill': 211,
 'start': 212,
 'us': 213,
 'years': 214,
 'read': 215,
 'others': 216,
 'yet': 217,
 'two': 218,
 'give': 219,
 'tell': 220,
 'may': 221,
 'place': 222,
 'same': 223,
 'write': 224,
 'since': 225,
 'nothing': 226,
 'end': 227,
 'heart': 228,
 'part': 229,
 'often': 230,
 'hate': 231,
 'stressed': 232,
 'strange': 233,
 'sweet': 234,
 'moment': 235,
 'morning': 236,
 'overwhelmed': 237,
 'hope': 238,
 'might': 239,
 'school': 240,
 'god': 241,
 'blog': 242,
 'anyone': 243,
 'didn': 244,
 'night': 245,
 'weird': 246,
 'put': 247,
 'id': 248,
 'hard': 249,
 'friend': 250,
 'guess': 251,
 'looking': 252,
 'stop': 253,
 'wanted': 254,
 'everyone': 255,
 'once': 256,
 'whole': 257,
 'point': 258,
 'sad': 259,
 'pain': 260,
 'does': 261,
 'thinking': 262,
 'angry': 263,
 'another': 264,
 'loved': 265,
 'old': 266,
 'excited': 267,
 'went': 268,
 'lost': 269,
 'hurt': 270,
 'amazing': 271,
 'blessed': 272,
 'done': 273,
 'each': 274,
 'writing': 275,
 'passionate': 276,
 'understand': 277,
 'body': 278,
 'talk': 279,
 'important': 280,
 'maybe': 281,
 'stupid': 282,
 'almost': 283,
 'completely': 284,
 'post': 285,
 'self': 286,
 'tired': 287,
 'least': 288,
 've': 289,
 'especially': 290,
 'next': 291,
 'helpless': 292,
 'accepted': 293,
 'free': 294,
 'must': 295,
 'use': 296,
 'past': 297,
 'best': 298,
 'leave': 299,
 'afraid': 300,
 'face': 301,
 'hated': 302,
 'mean': 303,
 'great': 304,
 'used': 305,
 'sense': 306,
 'agitated': 307,
 'cold': 308,
 'fact': 309,
 'thats': 310,
 'care': 311,
 'job': 312,
 'real': 313,
 'mind': 314,
 'starting': 315,
 'believe': 316,
 'inside': 317,
 'lately': 318,
 'else': 319,
 'girl': 320,
 'towards': 321,
 'found': 322,
 'sleep': 323,
 'totally': 324,
 'reason': 325,
 'strong': 326,
 'wasnt': 327,
 'taking': 328,
 'book': 329,
 'live': 330,
 'until': 331,
 'supporting': 332,
 'thankful': 333,
 'anxious': 334,
 'class': 335,
 'nervous': 336,
 'probably': 337,
 'low': 338,
 'glad': 339,
 'ok': 340,
 'generous': 341,
 'sorry': 342,
 'sort': 343,
 'become': 344,
 'share': 345,
 'loving': 346,
 'told': 347,
 'words': 348,
 'months': 349,
 'slightly': 350,
 'far': 351,
 'wonderful': 352,
 'head': 353,
 'saying': 354,
 'perfect': 355,
 'reading': 356,
 'kids': 357,
 'house': 358,
 'came': 359,
 'depressed': 360,
 'wish': 361,
 'safe': 362,
 'lonely': 363,
 'cool': 364,
 'frustrated': 365,
 'special': 366,
 'show': 367,
 'particularly': 368,
 'working': 369,
 'comfortable': 370,
 're': 371,
 'scared': 372,
 'man': 373,
 'coming': 374,
 'extremely': 375,
 'hear': 376,
 'guilty': 377,
 'child': 378,
 'horrible': 379,
 'fine': 380,
 'positive': 381,
 'bed': 382,
 'big': 383,
 'emotional': 384,
 'children': 385,
 'during': 386,
 'call': 387,
 'confident': 388,
 'run': 389,
 'amp': 390,
 'beloved': 391,
 'miserable': 392,
 'stuff': 393,
 'truly': 394,
 'hot': 395,
 'terrified': 396,
 'thoughts': 397,
 'exhausted': 398,
 'missed': 399,
 'cannot': 400,
 'eyes': 401,
 'lovely': 402,
 'proud': 403,
 'tortured': 404,
 'ashamed': 405,
 'living': 406,
 'finally': 407,
 'woke': 408,
 'control': 409,
 'liked': 410,
 'irritable': 411,
 'hours': 412,
 'mother': 413,
 'satisfied': 414,
 'room': 415,
 'anymore': 416,
 'havent': 417,
 'future': 418,
 'awkward': 419,
 'walk': 420,
 'admit': 421,
 'together': 422,
 'mad': 423,
 'close': 424,
 'content': 425,
 'selfish': 426,
 'seem': 427,
 'change': 428,
 'usually': 429,
 'story': 430,
 'lucky': 431,
 'successful': 432,
 'doesnt': 433,
 'disappointed': 434,
 'caring': 435,
 'spent': 436,
 'wrong': 437,
 'confused': 438,
 'experience': 439,
 'unsure': 440,
 'woman': 441,
 'miss': 442,
 'decided': 443,
 'wont': 444,
 'lethargic': 445,
 'amazed': 446,
 'super': 447,
 'fun': 448,
 'matter': 449,
 'somehow': 450,
 'instead': 451,
 'unhappy': 452,
 'bothered': 453,
 'funny': 454,
 'energy': 455,
 'longer': 456,
 'creative': 457,
 'inspired': 458,
 'mom': 459,
 'popular': 460,
 'knew': 461,
 'baby': 462,
 'seems': 463,
 'couldnt': 464,
 'side': 465,
 'embarrassed': 466,
 'small': 467,
 'shitty': 468,
 'vulnerable': 469,
 'annoyed': 470,
 'cute': 471,
 'full': 472,
 'somewhat': 473,
 'brave': 474,
 'talented': 475,
 'situation': 476,
 'enjoy': 477,
 'move': 478,
 'weeks': 479,
 'between': 480,
 'rest': 481,
 'running': 482,
 'ask': 483,
 'calm': 484,
 'idea': 485,
 'awful': 486,
 'rich': 487,
 'terrible': 488,
 'knowing': 489,
 'ago': 490,
 'convinced': 491,
 'both': 492,
 'hopeless': 493,
 'greedy': 494,
 'surprised': 495,
 'shaken': 496,
 'uncomfortable': 497,
 'punished': 498,
 'absolutely': 499,
 'needed': 500,
 'empty': 501,
 'uncertain': 502,
 'precious': 503,
 'irritated': 504,
 'fucked': 505,
 'hes': 506,
 'sit': 507,
 'money': 508,
 'comes': 509,
 'insecure': 510,
 'melancholy': 511,
 'impressed': 512,
 'discouraged': 513,
 'aching': 514,
 'wear': 515,
 'offended': 516,
 'happen': 517,
 'food': 518,
 'devastated': 519,
 'burdened': 520,
 'rejected': 521,
 'support': 522,
 'eat': 523,
 'asked': 524,
 'useful': 525,
 'hair': 526,
 'jealous': 527,
 'resentful': 528,
 'divine': 529,
 'violent': 530,
 'talking': 531,
 'soon': 532,
 'homesick': 533,
 'nice': 534,
 'sitting': 535,
 'wonder': 536,
 'simply': 537,
 'reluctant': 538,
 'dull': 539,
 'll': 540,
 'husband': 541,
 'pleasant': 542,
 'seeing': 543,
 'different': 544,
 'giving': 545,
 'watch': 546,
 'isolated': 547,
 'turn': 548,
 'women': 549,
 'open': 550,
 'happened': 551,
 'hopeful': 552,
 'however': 553,
 'beautiful': 554,
 'whether': 555,
 'cause': 556,
 'music': 557,
 'cranky': 558,
 'respected': 559,
 'youre': 560,
 'hand': 561,
 'paranoid': 562,
 'tonight': 563,
 'useless': 564,
 'began': 565,
 'kinda': 566,
 'rude': 567,
 'mine': 568,
 'gorgeous': 569,
 'rushed': 570,
 'apprehensive': 571,
 'assured': 572,
 'curious': 573,
 'stay': 574,
 'ways': 575,
 'theres': 576,
 'beaten': 577,
 'wanting': 578,
 'insulted': 579,
 'determined': 580,
 'pressured': 581,
 'honored': 582,
 'relaxed': 583,
 'ugly': 584,
 'sick': 585,
 'pissed': 586,
 'groggy': 587,
 'innocent': 588,
 'gloomy': 589,
 'valuable': 590,
 'guy': 591,
 'unwelcome': 592,
 'parents': 593,
 'took': 594,
 'ready': 595,
 'wronged': 596,
 'either': 597,
 'valued': 598,
 'gone': 599,
 'certain': 600,
 'dangerous': 601,
 'incredibly': 602,
 'honestly': 603,
 'watching': 604,
 'wake': 605,
 'numb': 606,
 'optimistic': 607,
 'set': 608,
 'dissatisfied': 609,
 'pathetic': 610,
 'needs': 611,
 'couple': 612,
 'faithful': 613,
 'against': 614,
 'intimidated': 615,
 'shy': 616,
 'blank': 617,
 'sympathetic': 618,
 'ignored': 619,
 'crappy': 620,
 'friendly': 621,
 'dumb': 622,
 'books': 623,
 'joyful': 624,
 'heartbroken': 625,
 'dirty': 626,
 'song': 627,
 'bitter': 628,
 'superior': 629,
 'worthless': 630,
 'cry': 631,
 'three': 632,
 'shes': 633,
 'relationship': 634,
 'disheartened': 635,
 'sincere': 636,
 'longing': 637,
 'smart': 638,
 'weekend': 639,
 'threatened': 640,
 'pleased': 641,
 'festive': 642,
 'realize': 643,
 'high': 644,
 'definitely': 645,
 'called': 646,
 'regretful': 647,
 'front': 648,
 'hesitant': 649,
 'lousy': 650,
 'www': 651,
 'listen': 652,
 'vain': 653,
 'mellow': 654,
 'trust': 655,
 'weight': 656,
 'delicious': 657,
 'joy': 658,
 'disturbed': 659,
 'clever': 660,
 'broke': 661,
 'naughty': 662,
 'upset': 663,
 'nostalgic': 664,
 'romantic': 665,
 'fake': 666,
 'supportive': 667,
 'd': 668,
 'shocked': 669,
 'bitchy': 670,
 'productive': 671,
 'damaged': 672,
 'ones': 673,
 'yesterday': 674,
 'eating': 675,
 'waiting': 676,
 'guys': 677,
 'humiliated': 678,
 'lives': 679,
 'etc': 680,
 'spend': 681,
 'fearful': 682,
 'fantastic': 683,
 'outside': 684,
 'resolved': 685,
 'distracted': 686,
 'true': 687,
 'drained': 688,
 'half': 689,
 'troubled': 690,
 'inadequate': 691,
 'hour': 692,
 'defeated': 693,
 'course': 694,
 'given': 695,
 'energetic': 696,
 'disgusted': 697,
 'whatever': 698,
 'tried': 699,
 'intelligent': 700,
 'suddenly': 701,
 'shaky': 702,
 'petty': 703,
 'listless': 704,
 'gentle': 705,
 'unimportant': 706,
 'trusting': 707,
 'fabulous': 708,
 'carefree': 709,
 'boring': 710,
 'second': 711,
 'whenever': 712,
 'relieved': 713,
 'rotten': 714,
 'welcomed': 715,
 'lame': 716,
 'skin': 717,
 'behind': 718,
 'generally': 719,
 'christmas': 720,
 'supposed': 721,
 'eager': 722,
 'deprived': 723,
 'needy': 724,
 'isnt': 725,
 'exactly': 726,
 'continue': 727,
 'single': 728,
 'deep': 729,
 'unfortunate': 730,
 'summer': 731,
 'suffering': 732,
 'list': 733,
 'grateful': 734,
 'under': 735,
 'buy': 736,
 'horny': 737,
 'rebellious': 738,
 'hold': 739,
 'impatient': 740,
 'play': 741,
 'adventurous': 742,
 'although': 743,
 'realized': 744,
 'doomed': 745,
 'plan': 746,
 'young': 747,
 'worthwhile': 748,
 'country': 749,
 'word': 750,
 'restless': 751,
 'toward': 752,
 'loyal': 753,
 'tender': 754,
 'thrilled': 755,
 'peaceful': 756,
 'order': 757,
 'virtuous': 758,
 'jaded': 759,
 'smile': 760,
 'girls': 761,
 'car': 762,
 'artistic': 763,
 'taken': 764,
 'deal': 765,
 'ungrateful': 766,
 'learned': 767,
 'mood': 768,
 'honoured': 769,
 'fear': 770,
 'invigorated': 771,
 'normal': 772,
 'students': 773,
 'using': 774,
 'forward': 775,
 'wasn': 776,
 'along': 777,
 'game': 778,
 'lack': 779,
 'frightened': 780,
 'boy': 781,
 'problems': 782,
 'movie': 783,
 'men': 784,
 'foolish': 785,
 'later': 786,
 'acceptable': 787,
 'saw': 788,
 'name': 789,
 'contented': 790,
 'abused': 791,
 'within': 792,
 'break': 793,
 'constantly': 794,
 'grumpy': 795,
 'sat': 796,
 'discontent': 797,
 'stand': 798,
 'telling': 799,
 'learn': 800,
 'seen': 801,
 'moving': 802,
 'emotions': 803,
 'smug': 804,
 'vital': 805,
 'beginning': 806,
 'lose': 807,
 'dream': 808,
 'moments': 809,
 'art': 810,
 'stomach': 811,
 'oh': 812,
 'triumphant': 813,
 'opportunity': 814,
 'delicate': 815,
 'fall': 816,
 'doesn': 817,
 'fond': 818,
 'desire': 819,
 'privileged': 820,
 'putting': 821,
 'learning': 822,
 'terrific': 823,
 'minutes': 824,
 'stubborn': 825,
 'hands': 826,
 'meet': 827,
 'easy': 828,
 'unloved': 829,
 'upon': 830,
 'submissive': 831,
 'age': 832,
 'casual': 833,
 'team': 834,
 'means': 835,
 'ecstatic': 836,
 'deeply': 837,
 'walked': 838,
 'type': 839,
 'reassured': 840,
 'begin': 841,
 'goes': 842,
 'piece': 843,
 'shit': 844,
 'wouldnt': 845,
 'src': 846,
 'worked': 847,
 'peace': 848,
 'human': 849,
 'bring': 850,
 'frantic': 851,
 'focus': 852,
 'worried': 853,
 'gets': 854,
 'looks': 855,
 'healthy': 856,
 'kept': 857,
 'worth': 858,
 'met': 859,
 'speak': 860,
 'imagine': 861,
 'won': 862,
 'yes': 863,
 'despite': 864,
 'group': 865,
 'touch': 866,
 'personal': 867,
 'walking': 868,
 'air': 869,
 'wearing': 870,
 'wants': 871,
 'red': 872,
 'possibly': 873,
 'loss': 874,
 'leaving': 875,
 'suppose': 876,
 'seriously': 877,
 'late': 878,
 'father': 879,
 'space': 880,
 'utterly': 881,
 'chance': 882,
 'phone': 883,
 'month': 884,
 'comments': 885,
 'appreciative': 886,
 'amount': 887,
 'possible': 888,
 'sentimental': 889,
 'skeptical': 890,
 'stories': 891,
 'strongly': 892,
 'finished': 893,
 'arms': 894,
 'across': 895,
 'attention': 896,
 'envious': 897,
 'due': 898,
 'tragic': 899,
 'damn': 900,
 'news': 901,
 'amused': 902,
 'heard': 903,
 'short': 904,
 'son': 905,
 'tears': 906,
 'perhaps': 907,
 'quickly': 908,
 'style': 909,
 'known': 910,
 'add': 911,
 'spending': 912,
 'recently': 913,
 'brain': 914,
 'questions': 915,
 'fucking': 916,
 'state': 917,
 'community': 918,
 'expect': 919,
 'unpleasant': 920,
 'truth': 921,
 'theyre': 922,
 'college': 923,
 'img': 924,
 'line': 925,
 'wondering': 926,
 'water': 927,
 'gave': 928,
 'keeping': 929,
 'worse': 930,
 'doubtful': 931,
 'personally': 932,
 'dazed': 933,
 'finish': 934,
 'crazy': 935,
 'top': 936,
 'disillusioned': 937,
 'delighted': 938,
 'picture': 939,
 'emotionally': 940,
 'pay': 941,
 'level': 942,
 'crying': 943,
 'themselves': 944,
 'sleeping': 945,
 'race': 946,
 'cut': 947,
 'act': 948,
 'voice': 949,
 'managed': 950,
 'party': 951,
 'sadness': 952,
 'spirit': 953,
 'decision': 954,
 'lots': 955,
 'messy': 956,
 'photos': 957,
 'four': 958,
 'usual': 959,
 'reasons': 960,
 'explain': 961,
 'distressed': 962,
 'everyday': 963,
 'trip': 964,
 'u': 965,
 'effort': 966,
 'stress': 967,
 'hostile': 968,
 'missing': 969,
 'physically': 970,
 'tomorrow': 971,
 'light': 972,
 'anger': 973,
 'death': 974,
 'decide': 975,
 'lazy': 976,
 'choice': 977,
 'wait': 978,
 'fairly': 979,
 'weather': 980,
 'hit': 981,
 'remorseful': 982,
 'listening': 983,
 'anyway': 984,
 'early': 985,
 'church': 986,
 'general': 987,
 'step': 988,
 'mostly': 989,
 'passed': 990,
 'tend': 991,
 'glamorous': 992,
 'please': 993,
 'keen': 994,
 'looked': 995,
 'gotten': 996,
 'forget': 997,
 'asking': 998,
 'issues': 999,
 'blogging': 1000,
 ...}

In [30]:
vocab_size = len(T.word_index)
print("Size of the vocabulary: ",vocab_size)

Size of the vocabulary:  15212

In [9]:
sentences_list = df_train['text'].tolist()
print(len(sentences_list))

16000

In [16]:
max_length = max(len(x.split()) for x in sentences_list)
print("Maximum length of sentence:",max_length)

longest_sentence = max(sentences_list, key=len)
print("Longest sentence:", longest_sentence)
print("Index:", sentences_list.index(longest_sentence))

Maximum length of sentence: 66
Longest sentence: i hope that those of you who actauly found this and read it feel possibly inspired to go out and buy some of these items or even go through storage and see what clothes of yours your mom saved and that you still have a hope of fitting in and mix up your wardrobe for this summer and have a little fun
Index: 10390

In [18]:
sequences = T.texts_to_sequences(sentences_list)

In [20]:
padded_sequences = pad_sequences(sequences, maxlen=max_length, padding='pre')
padded_sequences

array([[   0,    0,    0, ...,  138,    2,  678],
       [   0,    0,    0, ...,    3,   21, 1254],
       [   0,    0,    0, ...,    2,  494,  437],
       ...,
       [   0,    0,    0, ...,    3,  101, 1331],
       [   0,    0,    0, ...,  339,    8,   42],
       [   0,    0,    0, ...,   25, 3585,   12]], dtype=int32)

In [21]:
print(type(padded_sequences))

<class 'numpy.ndarray'>

In [24]:
X = padded_sequences
X.shape

(16000, 66)

In [25]:
y = df_train['label']
y.shape

(16000,)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from sklearn.model_selection import train_test_split

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:
model = Sequential()
model.add(Embedding(input_dim=15213, output_dim=8, input_length=max_length))
model.add(LSTM(64))
model.add(Dense(6, activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [35]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [36]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.fit(X,y,epochs=50)

Epoch 1/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 18s 31ms/step - accuracy: 0.3988 - loss: 1.5084
Epoch 2/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.7126 - loss: 0.8127
Epoch 3/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.8257 - loss: 0.4816
Epoch 4/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 31ms/step - accuracy: 0.8864 - loss: 0.3153
Epoch 5/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9352 - loss: 0.1967
Epoch 6/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9587 - loss: 0.1371
Epoch 7/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - accuracy: 0.9674 - loss: 0.1052
Epoch 8/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 31ms/step - accuracy: 0.9758 - loss: 0.0800
Epoch 9/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - accuracy: 0.9818 - loss: 0.0616
Epoch 10/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9831 - loss: 0.0559
Epoch 11/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.9818 - loss: 0.0565
Epoch 12/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.9846 - loss: 0.0488
Epoch 13/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.9861 - loss: 0.0394
Epoch 14/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.9901 - loss: 0.0303
Epoch 15/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.9914 - loss: 0.0256
Epoch 16/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 31ms/step - accuracy: 0.9851 - loss: 0.0472
Epoch 17/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 22s 33ms/step - accuracy: 0.9899 - loss: 0.0294
Epoch 18/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 31ms/step - accuracy: 0.9923 - loss: 0.0236
Epoch 19/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.9933 - loss: 0.0195
Epoch 20/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - accuracy: 0.9925 - loss: 0.0208
Epoch 21/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.9929 - loss: 0.0208
Epoch 22/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - accuracy: 0.9933 - loss: 0.0190
Epoch 23/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - accuracy: 0.9921 - loss: 0.0230
Epoch 24/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 31ms/step - accuracy: 0.9939 - loss: 0.0195
Epoch 25/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.9948 - loss: 0.0142
Epoch 26/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 15s 31ms/step - accuracy: 0.9956 - loss: 0.0126
Epoch 27/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - accuracy: 0.9939 - loss: 0.0172
Epoch 28/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9939 - loss: 0.0181
Epoch 29/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 31ms/step - accuracy: 0.9952 - loss: 0.0118
Epoch 30/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.9957 - loss: 0.0114
Epoch 31/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 31ms/step - accuracy: 0.9946 - loss: 0.0144
Epoch 32/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 22s 34ms/step - accuracy: 0.9939 - loss: 0.0174
Epoch 33/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.9941 - loss: 0.0150
Epoch 34/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.9952 - loss: 0.0109
Epoch 35/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9949 - loss: 0.0125
Epoch 36/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9959 - loss: 0.0097
Epoch 37/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9966 - loss: 0.0082
Epoch 38/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 34ms/step - accuracy: 0.9958 - loss: 0.0101
Epoch 39/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 19s 31ms/step - accuracy: 0.9961 - loss: 0.0084
Epoch 40/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9965 - loss: 0.0079
Epoch 41/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9965 - loss: 0.0086
Epoch 42/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.9941 - loss: 0.0157
Epoch 43/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 17s 33ms/step - accuracy: 0.9958 - loss: 0.0119
Epoch 44/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 32ms/step - accuracy: 0.9965 - loss: 0.0075
Epoch 45/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 21s 32ms/step - accuracy: 0.9967 - loss: 0.0067
Epoch 46/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9968 - loss: 0.0070
Epoch 47/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.9959 - loss: 0.0089
Epoch 48/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 32ms/step - accuracy: 0.9964 - loss: 0.0085
Epoch 49/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 16s 31ms/step - accuracy: 0.9963 - loss: 0.0089
Epoch 50/50
500/500 ━━━━━━━━━━━━━━━━━━━━ 20s 31ms/step - accuracy: 0.9966 - loss: 0.0081

In [38]:
model.evaluate(X_test, y_test)

100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9987 - loss: 0.0043

[0.004288120660930872, 0.9987499713897705]

In [40]:
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

label_map = {
    0: "sadness",
    1: "joy",
    2: "love",
    3: "anger",
    4: "fear",
    5: "surprise"
}

def predict_emotion(sentence, tokenizer, model, max_length, label_map):
    seq = tokenizer.texts_to_sequences([sentence])
    padded = pad_sequences(seq, maxlen=max_length, padding='pre')
    pred = model.predict(padded, verbose=0)
    pred_class = np.argmax(pred, axis=1)[0]
    return {
        "sentence": sentence,
        "processed_sequence": padded,
        "prediction_index": pred_class,
        "prediction_label": label_map[pred_class],
        "prediction_probabilities": pred[0]
    }

In [61]:
text = "i find myself in the odd position of feeling supportive of"
result = predict_emotion(text, T, model, max_length, label_map)

print("Sentence:", result["sentence"])
print("Predicted class index:", result["prediction_index"])
print("Predicted emotion:", result["prediction_label"])

Sentence: i find myself in the odd position of feeling supportive of
Predicted class index: 2
Predicted emotion: love

#### Testing on test.csv

In [62]:
df_test = pd.read_csv('/content/test.csv')
df_test.head()

                                                text  label
0  im feeling rather rotten so im not very ambiti...      0
1          im updating my blog because i feel shitty      0
2  i never make her separate from me because i do...      0
3  i left with my bouquet of red and yellow tulip...      1
4    i was feeling a little vain when i did this one      0

#### Preprocess test text with the same tokenizer

In [63]:
test_sentences = df_test['text'].tolist()
test_sequences = T.texts_to_sequences(test_sentences)
X_new_test = pad_sequences(test_sequences, maxlen=max_length, padding='pre')

#### Labels

In [64]:
y_new_test = df_test['label'].values

#### Evaluate

In [70]:
X_new_test = np.asarray(X_new_test, dtype=np.int32)
y_new_test = np.asarray(y_new_test, dtype=np.int32)

loss, accuracy = model.evaluate(X_new_test, y_new_test, verbose=1)
print("Loss:", loss)
print("Accuracy:", accuracy)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.9080 - loss: 0.4397
Loss: 0.43965256214141846
Accuracy: 0.9079999923706055

In [71]:
model.save("emotion_detection_model.keras")

In [72]:
from google.colab import drive
import pickle
drive.mount('/content/drive')

model.save("/content/drive/MyDrive/emotion_model.keras")

with open("/content/drive/MyDrive/tokenizer.pkl", "wb") as f:
    pickle.dump(T, f)

Mounted at /content/drive